GPU available: True, used: True
TPU available: False, using: 0 TPU cores
CUDA_VISIBLE_DEVICES: [0]
Using native 16bit precision.
Traceback (most recent call last):
  File "pl.py", line 402, in <module>
    trainer.fit(model)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 951, in fit
    self.scale_batch_size(model, mode=self.auto_scale_batch_size)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_tricks.py", line 139, in scale_batch_size
    raise MisconfigurationException(f'Field {batch_arg_name} not found in `model.hparams`')
pytorch_lightning.utilities.exceptions.MisconfigurationException: Field batch_size not found in `model.hparams`
